package eu.majmohar.isrm
import android.os.Bundle
import android.view.View
import android.widget.*
import androidx.appcompat.app.*
import java.time.*
import java.time.format.DateTimeFormatter
import java.util.concurrent.Executors
class MainActivity:AppCompatActivity(){
 private val executor=Executors.newSingleThreadExecutor();private lateinit var repo:TimetableRepository;private lateinit var list:LinearLayout;private lateinit var progress:ProgressBar;private lateinit var subtitle:TextView;private var week=LocalDate.now().with(DayOfWeek.MONDAY);private val prefs by lazy{getSharedPreferences("native-settings",MODE_PRIVATE)};private val year get()=prefs.getString("year","1")?:"1";private val student get()=prefs.getString("student","")?:""
 override fun onCreate(s:Bundle?){super.onCreate(s);setContentView(R.layout.activity_main);repo=TimetableRepository(this);list=findViewById(R.id.lessons);progress=findViewById(R.id.loading);subtitle=findViewById(R.id.week_subtitle);findViewById<View>(R.id.previous).setOnClickListener{week=week.minusWeeks(1);load()};findViewById<View>(R.id.next).setOnClickListener{week=week.plusWeeks(1);load()};findViewById<View>(R.id.today).setOnClickListener{week=LocalDate.now().with(DayOfWeek.MONDAY);load()};findViewById<View>(R.id.refresh).setOnClickListener{load()};findViewById<View>(R.id.settings).setOnClickListener{settings()};if(android.os.Build.VERSION.SDK_INT>=33)onBackInvokedDispatcher.registerOnBackInvokedCallback(android.window.OnBackInvokedDispatcher.PRIORITY_DEFAULT){finish()};load();checkRelease() }
 private fun load(){subtitle.text="${week.format(DateTimeFormatter.ofPattern("d. M."))} — ${week.plusDays(4).format(DateTimeFormatter.ofPattern("d. M."))} · $year. letnik";render(repo.cached(week,year,student));progress.visibility=View.VISIBLE;executor.execute{val fresh=runCatching{repo.refresh(week,year,student)}.getOrElse{repo.cached(week,year,student)};runOnUiThread{render(fresh);progress.visibility=View.GONE};executor.execute{repo.preload(year,student)}}}
 private fun render(items:List<Lesson>){list.removeAllViews();(0..4).forEach{offset->val day=week.plusDays(offset.toLong());list.addView(TextView(this).apply{text=day.format(DateTimeFormatter.ofPattern("EEEE · d. MMMM"));setTextColor(0xffeef2eb.toInt());textSize=18f;setPadding(0,24,0,9)});val today=items.filter{it.date==day.toString()};if(today.isEmpty())list.addView(TextView(this).apply{text="Brez obveznosti";setTextColor(0xff9ca8a0.toInt());setPadding(0,0,0,8)})else today.forEach{list.addView(card(it))}}}
 private fun card(x:Lesson)=TextView(this).apply{text="${x.start}–${x.end}   ${x.title}\n${x.source} · ${x.type} · ${x.room.ifBlank{"Prostor ni znan"}}";setTextColor(if(x.source=="FRI")0xfff0c2af.toInt() else 0xffb9e2d9.toInt());setBackgroundResource(if(x.source=="FRI")R.drawable.lesson_fri else R.drawable.lesson_fmf);setPadding(18,14,18,14);textSize=15f;setOnClickListener{AlertDialog.Builder(this@MainActivity).setTitle(x.title).setMessage("${x.start}–${x.end}\n${x.room}\n${x.teacher.ifBlank{"Izvajalec ni naveden"}}\n${x.source}").setPositiveButton("Zapri",null).show()};layoutParams=LinearLayout.LayoutParams(-1,-2).apply{bottomMargin=8}}
 private fun settings(){val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(56,8,56,0)};val years=Spinner(this).apply{adapter=ArrayAdapter(this@MainActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("1. letnik","2. letnik","3. letnik"));setSelection(year.toInt()-1)};val no=EditText(this).apply{hint="Vpisna številka (neobvezno)";inputType=2;setText(student)};box.addView(years);box.addView(no);AlertDialog.Builder(this).setTitle("Nastavitve urnika").setView(box).setNegativeButton("Prekliči",null).setPositiveButton("Shrani"){_,_->prefs.edit().putString("year",(years.selectedItemPosition+1).toString()).putString("student",no.text.toString().filter(Char::isDigit)).apply();load()}.show()}
 private fun newer(remote:String,local:String):Boolean { val a=remote.split('.').map{it.toIntOrNull()?:0};val b=local.split('.').map{it.toIntOrNull()?:0};for(i in 0 until maxOf(a.size,b.size)){val x=a.getOrElse(i){0};val y=b.getOrElse(i){0};if(x!=y)return x>y};return false }
 private fun checkRelease(){executor.execute{val update=runCatching{val r=org.json.JSONObject(java.net.URL("${BuildConfig.WEB_APP_URL.trimEnd('/')}/api/release").readText());r.optString("androidVersion") to r.optString("androidApkUrl")}.getOrNull()?:return@execute;if(newer(update.first,BuildConfig.VERSION_NAME))runOnUiThread{AlertDialog.Builder(this).setTitle("Na voljo je posodobitev IŠRM").setMessage("Različica ${update.first} je pripravljena.").setNegativeButton("Kasneje",null).setPositiveButton("Odpri prenos"){_,_->val uri=android.net.Uri.parse(update.second);if(uri.scheme=="https")startActivity(android.content.Intent(android.content.Intent.ACTION_VIEW,uri))}.show()}}}
 override fun onDestroy(){executor.shutdownNow();super.onDestroy()}
}
